version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    env_file:
      - ./.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static_volume:/backend/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/backend/static
    depends_on:
      - backend

  redis:
    image: redis:alpine
    hostname: redis
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8079:8001'
    volumes:
      - redis_insight_volume:/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

volumes:
  postgres_data: {}
  static_volume: {}
  redis_volume: {}
  redis_insight_volume: {}
